source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails', '~> 5.0.0'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

gem 'materialize-sass', '~> 0.97.6'

gem 'devise', '~> 4.1.1'

group :development, :test do
  gem 'pry', '~> 0.10.4'
  gem 'rspec-rails', '~> 3.5.1'
  gem 'rails-controller-testing', '~> 0.1.1'
  gem 'shoulda-matchers', '~> 3.1.1'
  gem 'database_cleaner', '~> 1.5.3'
  gem 'simplecov', '~> 0.12.0'
  gem 'factory_girl_rails', '~> 4.7.0'
  gem 'capybara', '~> 2.7.1'
  gem 'selenium-webdriver', '~> 2.53.4'
end

group :development do
  gem 'annotate', '~> 2.7.1' 
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]