# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96ff74e55724b45360f62c0813f17a9644b77f710341553b6d5c6960f729ea94caa1e28569afcb4beb944eff130b55eea3d32c1ac5f4d22e544421042172be0d

test:
  secret_key_base: a9d33f4e61a7594ed1ace3dee88ae212a11a2d0c47bf948a3fef9ec6fa311cb23c5087264ed11ba674d579c19a5b5492afaa07305370e83b0f8340a2c826dc9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
